BookService/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using BookService.Areas.HelpPage.ModelDescriptions;
using BookService.Areas.HelpPage.Models;

namespace BookService.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

BookService/Controllers/AssemblyRequestsController.cs
using BookService.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrethrenDirectory.Controllers
{
    [MyAuthFilter]
    public class AssemblyRequestsController : Controller
    {
        // GET: AssemblyRequests
        public ActionResult Index()
        {
            return View();
        }

        // GET: Employee/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.RequestId = id;
            return View();
        }
    }
}

BookService/Controllers/EvangelistController.cs
using BookService.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookService.Controllers
{
    [MyAuthFilter]
    public class EvangelistController : Controller
    {
        // GET: Evangelist
        public ActionResult Index()
        {
            return View();
        }

        // GET: Employee/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.SelectedEvangelistId = id;
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }
    }
}

BookService/Controllers/EvangelistRequestsController.cs
using BookService.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrethrenDirectory.Controllers
{
    [MyAuthFilter]
    public class EvangelistRequestsController : Controller
    {
        // GET: EvangelistRequests
        public ActionResult Index()
        {
            return View();
        }

        // GET: Employee/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.RequestId = id;
            return View();
        }
    }
}

BookService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
 
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Brethren Network", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Assemblies", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Evangelists", "Index", "Evangelist", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Assembly Requests", "Index", "AssemblyRequests", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Evangelist Requests", "Index", "EvangelistRequests", new { area = "" }, null)</li>
                    <!--<li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>-->
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Designed and Developed By Vincent Kola</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="http://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script type="text/javascript">
        var loginusername = '@(((BrethrenModels.UserMaster)Session["UserInfo"]).UserName)';
        var loginpassword = '@(((BrethrenModels.UserMaster)Session["UserInfo"]).UserPassword)';
    </script>
    <script src="~/Scripts/EvangelistJs/tokenhelper.js"></script>
</body>
</html>

BookService/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="http://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
</body>
</html>